Fix handling of UNIX sockaddr path lengths.
Under linux, sockaddr_un does not have a length field, but the nix Rust
wrapper for it does keep track of the length, and this must be managed
correctly or else UnixAddr::path() will return strings that are too
long. Without this change I get either:

Error: Failed to listen on /var/lib/erbium/control<binary garbage>:
path must be shorter than libc::sockaddr_un.sun_path

or

Error: Failed to cleanup /var/lib/erbium/control: file name contained
an unexpected NUL byte

Prior to the resolution of https://github.com/nix-rust/nix/issues/1800
passing the maximum size of a sockaddr_un path was probably the right
thing to do, but now it seems it is no longer correct, and furthermore
there is now a .as_unix_addr() method on SockaddrStorage.